<?php
$_helper = $this->helper('magecomm_dummyadmin');
$category = Mage::registry('current_category');
$categoryImage = $this->getCategoryImage($category); ?>

<header class="cat-title">
    <h1><?php echo $category->getCategory_name(); ?></h1>
    <?php if($category->getCategory_image()): ?>
        <div class="cat-img"><img width="100%" height="300px" alt="" src="<?php echo $categoryImage; ?>"/></div>
    <?php endif; ?>
</header>
<main class="category-content category-row">
    <?php
    $recentPostsByCategory= Mage::getModel('magecomm_dummyadmin/recentposts')->_getRecentCollection(3, $category->getCategory_id());
    if($recentPostsByCategory): ?>
    <div class="cat-posts <?php if(count($recentPostsByCategory)<3): ?>fjc-fs<?php else: ?>fjc-sb<?php endif; ?>">
        <?php
        foreach($recentPostsByCategory as $rpost): ?>

            <div class="post">
                <?php if($rpost->getPost_name()): ?>
                    <h3 class="post-name"><a href="<?php echo __($rpost->getPost_url());?>"><?php echo __($rpost->getPost_name()); ?></a></h3>
                <?php endif; ?>
                <div class="post-img">
                    <?php if($rpost->getPost_image()): ?>
                        <img src="<?php echo Mage::getBaseUrl('media'). $rpost->getPost_image(); ?>" width="380px" height="250px" alt=""/>
                    <?php else: ?>
                        <img src="<?php echo $_helper->getDefaultImage(); ?>" width="380px" height="250px" alt=""/>
                    <?php endif; ?>
                </div>
                <?php if($rpost->getPost_short_content()): ?>
                    <div class="post-excerpt">
                        <p><?php echo __($rpost->getPost_short_content());?></p>
                        <a class="read-more" target="_blank" href="<?php echo __($rpost->getPost_url());?>">Read more</a>
                    </div>
                <?php endif; ?>
            </div>
        <?php
        endforeach; ?>
    </div>
    <?php endif; ?>
</main>