<?php
$category = Mage::registry('current_category');
$getMetaTitle = $category->getCategory_name();
$getMetaImage = $this->getCategoryImage($category);
?>

    <link rel="canonical" href="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>"/>
    <meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?php echo $getMetaTitle; ?>" />

<?php if ($getMetaImage) { ?>
    <meta property="og:image" content="<?php echo $getMetaImage; ?>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="300" />
<?php } ?>