<?php
$post = Mage::registry('current_post');
$postImage = $this->getPostImage($post); ?>

<div class="dummyadmin">
    <header class="post-header">
        <h1><?php echo $post->getPost_name(); ?></h1>
    </header>

    <main class="post-content">
        <?php if($postImage): ?>
            <div class="post-img"><img alt="" src="<?php echo $postImage ?>"/></div>
        <?php endif; ?>
        <p class="post-text"><?php echo $post->getPost_content(); ?></p>
    </main>
</div>