<?php
$post = Mage::registry('current_post');
$getMetaTitle = $post->getPost_name();
$getMetaDescription = substr(strip_tags($post->getPost_short_content()), 0, 140) . '..';
$getMetaImage = $this->getPostImage($post);
?>

    <link rel="canonical" href="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>"/>
    <meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?php echo $getMetaTitle; ?>" />
    <meta property="og:description" content="<?php echo $getMetaDescription; ?>" />

<?php if ($getMetaImage) { ?>
    <meta property="og:image" content="<?php echo $getMetaImage; ?>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
<?php } ?>