<h3 class="dummyadmin-title">Menage Dummy Admin Blog Page</h3>
<div class="dummyadmin-links">
    <a href="<?php echo Mage::getUrl('adminhtml') . 'categories/index/key/b678091b6464341f01f2cd4000c01077/';?>">Categories</a>
    <a href="<?php echo Mage::getUrl('adminhtml') . 'posts/index/key/e6a1c4a51be0281248ca67637ccb4bf9/';?>">Posts</a>
    <a href="<?php echo Mage::getUrl('adminhtml') . 'system_config/edit/section/dummyadmin/key/e77e599c87238bfdd9e0493fb7149a7b/';?>">Config</a>
</div>

